<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>plan</string>
	</array>
	<key>name</key>
	<string>ZeroPlanFile</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(ROUTE)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(GET|POST|PUT|DELETE)</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#(.*)</string>
			<key>name</key>
			<string>comment.line.number-sign.plan</string>
		</dict>
		<dict>
			<key>match</key>
			<string>( \/[a-zA-Z\/{}_:\\+*]*)</string>
			<key>name</key>
			<string>entity.name.function.plan</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.plan</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\&lt;([A-Za-z\\]+)</string>
			<key>name</key>
			<string>entity.name.tag.plan</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\&lt;\&gt;]</string>
			<key>name</key>
			<string>entity.name.tag.plan</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\([A-Za-z\\]*\))</string>
			<key>name</key>
			<string>entity.name.type.plan</string>
		</dict>
		<dict>
			<key>match</key>
			<string> \[[A-Za-z0-9=]*\]</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\*([A-Za-z][A-Za-z0-9_\.\\]+)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.type</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\!([A-Za-z][A-Za-z0-9_\.\\]+)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\@([A-Za-z][A-Za-z0-9_\.\\]+)</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\$([A-Za-z][A-Za-z0-9_\.\\]*)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.plan</string>
	<key>uuid</key>
	<string>8edd1013-1e17-41d9-836b-f3e11666cf3c</string>
</dict>
</plist>
